name: Format with Prettier

on:
    workflow_dispatch:

jobs:
    format:
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Format code
              run: npm run format

            - name: Commit changes
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m "Format code with Prettier"
                  git push
